
var quadstick_buttons = {
    "MP Left Sip": "mp_left_sip",
    "MP Left Puff": "mp_left_puff",
    "MP Center Sip": "mp_center_sip",
    "MP Center Puff": "mp_center_puff",
    "MP Right Sip": "mp_right_sip",
    "MP Right Puff": "mp_right_puff",
    "MP Left Center Sip": "mp_left_center_sip",
    "MP Left Center Puff": "mp_left_center_puff",
    "MP Right Center Sip": "mp_right_center_sip",
    "MP Right Center Puff": "mp_right_center_puff",
    "MP Left Right Sip": "mp_left_right_sip",
    "MP Left Right Puff": "mp_left_right_puff",
    "MP Triple Sip": "mp_triple_sip",
    "MP Triple Puff": "mp_triple_puff",
    "MP Left Sip (Soft)": "mp_left_sip_soft",
    "MP Left Puff (Soft)": "mp_left_puff_soft",
    "MP Center Sip (Soft)": "mp_center_sip_soft",
    "MP Center Puff (Soft)": "mp_center_puff_soft",
    "MP Right Sip (Soft)": "mp_right_sip_soft",
    "MP Right Puff (Soft)": "mp_right_puff_soft",
    "MP Left Center Sip (Soft)": "mp_left_center_sip_soft",
    "MP Left Center Puff (Soft)": "mp_left_center_puff_soft",
    "MP Right Center Sip (Soft)": "mp_right_center_sip_soft",
    "MP Right Center Puff (Soft)": "mp_right_center_puff_soft",
    "MP Left Right Sip (Soft)": "mp_left_right_sip_soft",
    "MP Left Right Puff (Soft)": "mp_left_right_puff_soft",
    "MP Triple Sip (Soft)": "mp_triple_sip_soft",
    "MP Triple Puff (Soft)": "mp_triple_puff_soft",
    "Right Sip": "right_sip",
    "Right Puff": "right_puff",
    "Right Sip (Soft)": "right_sip_soft",
    "Right Puff (Soft)": "right_puff_soft",
    "Right Sip (Long)": "right_sip_long",
    "Right Puff (Long)": "right_puff_long",
    "Lip Movement": "lip",
    "Lip Movement (Soft)": "lip_soft",
};

var ps_controller_buttons = {
    "PS D-Pad Button North": "dpad_N",
    "PS D-Pad Buttons North and East": "dpad_NE",
    "PS D-Pad Button East": "dpad_E",
    "PS D-Pad Buttons South and East": "dpad_SE",
    "PS D-Pad Button South": "dpad_S",
    "PS D-Pad Buttons South and West": "dpad_SW",
    "PS D-Pad Button West": "dpad_W",
    "PS D-Pad Buttons North and West": "dpad_NW",
    "PS Left Joystick Left side": "left_joy_left",
    "PS Left Joystick Right side": "left_joy_right",
    "PS Left Joystick Up": "left_joy_up",
    "PS Left Joystick Down": "left_joy_down",
    "PS Right Joystick Left side": "right_joy_left",
    "PS Right Joystick Right side": "right_joy_right",
    "PS Right Joystick Up": "right_joy_up",
    "PS Right Joystick Down": "right_joy_down",
    "PS Left Button 1": "left_1",
    "PS Left Button 2 (trigger)": "left_2",
    "PS Left Button 3 (Press joystick)": "left_3",
    "PS Right Button 1": "right_1",
    "PS Right Button 2 (trigger)": "right_2",
    "PS Right Button 3 (Press joystick)": "right_3",
    "PS Button X": "x",
    "PS Button Square": "square",
    "PS Button Triangle": "triangle",
    "PS Button Circle": "circle",
    "PS Home": "ps3",
    "PS Select or Share": "select",
    "PS Start": "start",
};