var controller_types = ["PS3", "PS4", "PS5", "Xbox 360", "Xbox One", "Xbox Series X", "Nintendo Switch"]

var quadstick_buttons = {
    "Medium Pressure Left Sip": "mp_left_sip",
    "Medium Pressure Left Puff": "mp_left_puff",
    "Medium Pressure Center Sip": "mp_center_sip",
    "Medium Pressure Center Puff": "mp_center_puff",
    "Medium Pressure Right Sip": "mp_right_sip",
    "Medium Pressure Right Puff": "mp_right_puff",
    "Medium Pressure Left Center Sip": "mp_left_center_sip",
    "Medium Pressure Left Center Puff": "mp_left_center_puff",
    "Medium Pressure Right Center Sip": "mp_right_center_sip",
    "Medium Pressure Right Center Puff": "mp_right_center_puff",
    "Medium Pressure Left Right Sip": "mp_left_right_sip",
    "Medium Pressure Left Right Puff": "mp_left_right_puff",
    "Medium Pressure Triple Sip": "mp_triple_sip",
    "Medium Pressure Triple Puff": "mp_triple_puff",
    "Medium Pressure Left Sip (Soft)": "mp_left_sip_soft",
    "Medium Pressure Left Puff (Soft)": "mp_left_puff_soft",
    "Medium Pressure Center Sip (Soft)": "mp_center_sip_soft",
    "Medium Pressure Center Puff (Soft)": "mp_center_puff_soft",
    "Medium Pressure Right Sip (Soft)": "mp_right_sip_soft",
    "Medium Pressure Right Puff (Soft)": "mp_right_puff_soft",
    "Medium Pressure Left Center Sip (Soft)": "mp_left_center_sip_soft",
    "Medium Pressure Left Center Puff (Soft)": "mp_left_center_puff_soft",
    "Medium Pressure Right Center Sip (Soft)": "mp_right_center_sip_soft",
    "Medium Pressure Right Center Puff (Soft)": "mp_right_center_puff_soft",
    "Medium Pressure Left Right Sip (Soft)": "mp_left_right_sip_soft",
    "Medium Pressure Left Right Puff (Soft)": "mp_left_right_puff_soft",
    "Medium Pressure Triple Sip (Soft)": "mp_triple_sip_soft",
    "Medium Pressure Triple Puff (Soft)": "mp_triple_puff_soft",
    "Right Sip": "right_sip",
    "Right Puff": "right_puff",
    "Right Sip (Soft)": "right_sip_soft",
    "Right Puff (Soft)": "right_puff_soft",
    "Right Sip (Long)": "right_sip_long",
    "Right Puff (Long)": "right_puff_long",
    "Lip Movement": "lip",
    "Lip Movement (Soft)": "lip_soft",
    "Move Left": "left",
    "Move Right": "right",
    "Move Up": "up",
    "Move Down": "down",
    "Move in Any Direction": "any_direction",
    "Move North": "N",
    "Move Northeast": "NE",
    "Move East": "E",
    "Move Southeast": "SE",
    "Move South": "S",
    "Move Southwest": "SW",
    "Move West": "W",
    "Move Northwest": "NW",
    "Move North (Inner)": "N_inner",
    "Move Northeast (Inner)": "NE_inner",
    "Move East (Inner)": "E_inner",
    "Move Southeast (Inner)": "SE_inner",
    "Move South (Inner)": "S_inner",
    "Move Southwest (Inner)": "SW_inner",
    "Move West (Inner)": "W_inner",
    "Move Northwest (Inner)": "NW_inner",
    "USB 1 Move Left": "usb_1_left",
    "USB 1 Move Right": "usb_1_right",
    "USB 1 Move Up": "usb_1_up",
    "USB 1 Move Down": "usb_1_down",
    "USB 1 Move North": "usb_1_N",
    "USB 1 Move Northeast": "usb_1_NE",
    "USB 1 Move East": "usb_1_E",
    "USB 1 Move Southeast": "usb_1_SE",
    "USB 1 Move South": "usb_1_S",
    "USB 1 Move Southwest": "usb_1_SW",
    "USB 1 Move West": "usb_1_W",
    "USB 1 Move Northwest": "usb_1_NW",
    "USB 1 Move North (Inner)": "usb_1_N_inner",
    "USB 1 Move Northeast (Inner)": "usb_1_NE_inner",
    "USB 1 Move East (Inner)": "usb_1_E_inner",
    "USB 1 Move Southeast (Inner)": "usb_1_SE_inner",
    "USB 1 Move South (Inner)": "usb_1_S_inner",
    "USB 1 Move Southwest (Inner)": "usb_1_SW_inner",
    "USB 1 Move West (Inner)": "usb_1_W_inner",
    "USB 1 Move Northwest (Inner)": "usb_1_NW_inner",
    "USB 2 Move Left": "usb_2_left",
    "USB 2 Move Right": "usb_2_right",
    "USB 2 Move Up": "usb_2_up",
    "USB 2 Move Down": "usb_2_down",
    "USB 2 Move North": "usb_2_N",
    "USB 2 Move Northeast": "usb_2_NE",
    "USB 2 Move East": "usb_2_E",
    "USB 2 Move Southeast": "usb_2_SE",
    "USB 2 Move South": "usb_2_S",
    "USB 2 Move Southwest": "usb_2_SW",
    "USB 2 Move West": "usb_2_W",
    "USB 2 Move Northwest": "usb_2_NW",
    "USB 2 Move North (Inner)": "usb_2_N_inner",
    "USB 2 Move Northeast (Inner)": "usb_2_NE_inner",
    "USB 2 Move East (Inner)": "usb_2_E_inner",
    "USB 2 Move Southeast (Inner)": "usb_2_SE_inner",
    "USB 2 Move South (Inner)": "usb_2_S_inner",
    "USB 2 Move Southwest (Inner)": "usb_2_SW_inner",
    "USB 2 Move West (Inner)": "usb_2_W_inner",
    "USB 2 Move Northwest (Inner)": "usb_2_NW_inner",
    "USB 1 Button 1": "usb_1_button_1",
    "USB 1 Button 2": "usb_1_button_2",
    "USB 1 Button 3": "usb_1_button_3",
    "USB 1 Button 4": "usb_1_button_4",
    "USB 1 Button 5": "usb_1_button_5",
    "USB 1 Button 6": "usb_1_button_6",
    "USB 1 Button 7": "usb_1_button_7",
    "USB 1 Button 8": "usb_1_button_8",
    "USB 1 Button 9": "usb_1_button_9",
    "USB 1 Button 10": "usb_1_button_10",
    "USB 1 Button 11": "usb_1_button_11",
    "USB 1 Button 12": "usb_1_button_12",
    "USB 1 Button 13": "usb_1_button_13",
    "USB 1 Button 14": "usb_1_button_14",
    "USB 1 Button 15": "usb_1_button_15",
    "USB 2 Button 1": "usb_2_button_1",
    "USB 2 Button 2": "usb_2_button_2",
    "USB 2 Button 3": "usb_2_button_3",
    "USB 2 Button 4": "usb_2_button_4",
    "USB 2 Button 5": "usb_2_button_5",
    "USB 2 Button 6": "usb_2_button_6",
    "USB 2 Button 7": "usb_2_button_7",
    "USB 2 Button 8": "usb_2_button_8",
    "USB 2 Button 9": "usb_2_button_9",
    "USB 2 Button 10": "usb_2_button_10",
    "USB 2 Button 11": "usb_2_button_11",
    "USB 2 Button 12": "usb_2_button_12",
    "USB 2 Button 13": "usb_2_button_13",
    "USB 2 Button 14": "usb_2_button_14",
    "USB 2 Button 15": "usb_2_button_15",
    "Digital Input 1": "digital_in_1",
    "Digital Input 2": "digital_in_2",
    "Digital Input 3": "digital_in_3",
    "Digital Input 4": "digital_in_4",
    "Digital Input 5": "digital_in_5",
    "Digital Input 6": "digital_in_6",
    "Digital Input 7": "digital_in_7",
    "Digital Input 8": "digital_in_8",
    "Center": "center",
    "Constant": "constant"
};

var ps_controller_buttons = {
    "PS D-Pad Button North": "dpad_N",
    "PS D-Pad Buttons North and East": "dpad_NE",
    "PS D-Pad Button East": "dpad_E",
    "PS D-Pad Buttons South and East": "dpad_SE",
    "PS D-Pad Button South": "dpad_S",
    "PS D-Pad Buttons South and West": "dpad_SW",
    "PS D-Pad Button West": "dpad_W",
    "PS D-Pad Buttons North and West": "dpad_NW",
    "PS Left Joystick Left side": "left_joy_left",
    "PS Left Joystick Right side": "left_joy_right",
    "PS Left Joystick Up": "left_joy_up",
    "PS Left Joystick Down": "left_joy_down",
    "PS Right Joystick Left side": "right_joy_left",
    "PS Right Joystick Right side": "right_joy_right",
    "PS Right Joystick Up": "right_joy_up",
    "PS Right Joystick Down": "right_joy_down",
    "PS Left Button 1": "left_1",
    "PS Left Button 2 (trigger)": "left_2",
    "PS Left Button 3 (Press joystick)": "left_3",
    "PS Right Button 1": "right_1",
    "PS Right Button 2 (trigger)": "right_2",
    "PS Right Button 3 (Press joystick)": "right_3",
    "PS Button X": "x",
    "PS Button Square": "square",
    "PS Button Triangle": "triangle",
    "PS Button Circle": "circle",
    "PS Home": "ps3",
    "PS Select or Share": "select",
    "PS Start": "start",
    "PS motion sensor to right": "acceleration_x_right",
    "PS motion sensor to left": "acceleration_x_left",
    "PS motion sensor away from player": "acceleration_y_fore",
    "PS motion sensor towards player": "acceleration_y_aft",
    "PS motion sensor up": "acceleration_z_up",
    "PS motion sensor down": "acceleration_z_down",
    "PS gyroscope clockwise": "gyroscope_x_cw",
    "PS gyroscope counter clockwise": "gyroscope_x_ccw",
    "PS gyroscope clockwise": "gyroscope_y_cw",
    "PS gyroscope counter clockwise": "gyroscope_y_ccw",
    "PS gyroscope clockwise": "gyroscope_z_cw",
    "PS gyroscope counter clockwise": "gyroscope_z_ccw",
    "Mouse Left movement": "mouse_left",
    "Mouse Right movement": "mouse_right",
    "Mouse Up movement": "mouse_up",
    "Mouse Down movement": "mouse_down",
    "Mouse Wheel Up rotation": "mouse_wheel_up",
    "Mouse Wheel Down rotation": "mouse_wheel_down",
    "Mouse Pan Left tilt": "mouse_pan_left",
    "Mouse Pan Right tilt": "mouse_pan_right",
    "Mouse Button Back": "mouse_back",
    "Mouse Button Forward": "mouse_forward",
    "Mouse Button Left": "mouse_left_button",
    "Mouse Button Right": "mouse_right_button",
    "Mouse Button Middle": "mouse_middle_button",
    "Digital Out 1 turn on": "digital_out1_on",
    "Digital Out 1 turn off": "digital_out1_off",
    "Digital Out 1 toggle state": "digital_out1_toggle",
    "Digital Out 2 turn on": "digital_out2_on",
    "Digital Out 2 turn off": "digital_out2_off",
    "Digital Out 2 toggle state": "digital_out2_toggle",
    "LEDs Brighter": "brightness_up",
    "LEDs Dimmer": "brightness_down",
    "Speaker increase volume": "volume_up",
    "Speaker decrease volume": "volume_down",
    "Change to next profile": "increment_mode",
    "Change to previous profile": "decrement_mode",
    "Invoke the file selection process": "load_file",
    "Force a complete restart of the quadstick": "reset_quadstick",
    "Force the USB to quickly reconnect": "ps4_authentication",
    "Xmit IR code from command table - TV Channel Up": "ir_tv_channel_up",
    "Xmit IR code from command table - TV Channel Down": "ir_tv_channel_down",
    "Xmit IR code from command table - TV Volume Up": "ir_tv_volume_up",
    "Xmit IR code from command table - TV Volume Down": "ir_tv_volume_down",
    "Xmit IR code from command table - TV On/Off": "ir_tv_on_off",
    "Xmit IR code from command table - TV Select Input": "ir_tv_select_input",
    "Xmit IR code from command table": "ir_play",
    "Xmit IR code from command table": "ir_stop",
    "Xmit IR code from command table": "ir_fast_forward",
    "Xmit IR code from command table": "ir_rewind",
    "Xmit IR code from command table": "ir_skip_forward",
    "Xmit IR code from command table": "ir_skip_back",
    "Xmit IR code from command table": "ir_record",
    "Xmit IR code from command table": "ir_pause",
    "Xmit IR code from command table": "ir_mute",
    "Xmit IR code from command table": "ir_guide",
    "Xmit IR code from command table": "ir_menu",
    "Xmit IR code from command table": "ir_cancel",
    "Xmit IR code from command table": "ir_select",
    "Xmit IR code from command table": "ir_up",
    "Xmit IR code from command table": "ir_down",
    "Xmit IR code from command table": "ir_left",
    "Xmit IR code from command table": "ir_right",
    "Xmit IR code from command table": "ir_aux1",
    "Xmit IR code from command table": "ir_aux2",
    "Xmit IR code from command table": "ir_aux3",
    "Xmit IR code from command table": "ir_aux4",
    "Keyboard send key": "kb_a",
    "Keyboard send key": "kb_b",
    // ...
};